# WRP-HubStatus Configuration
plugin:
  enabled: true
  language: "es"
  show-license: true

# Global item settings
item-defaults:
  world: "world"
  material: PLAYER_HEAD
  enchanted: true
  unmovable: true
  command: "server %server%"

# List of servers to monitor
servers:
  survival:
    display-name: "Survival"
    address: "127.0.0.1:25565" # Change to real IP:Port
    max-players: 100
    auto-status: true # If true, it will ping the address
    default-state: "OFFLINE"
    item:
      enabled: true
      slot: 4
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmFkYmE0MzY3MTM2YmFhYzFmNzY3Y2E3Y2IwZTU3N2UyYWUzYzFkYjQ5MWFjZThmNGRiM2Y4OTVjYzhkZDIifX19"
      name: "&6&lWRP Survival &7(Click)"
  skyblock:
    display-name: "Skyblock"
    address: "127.0.0.1:25566"
    max-players: 50
    auto-status: false # Manual status
    default-state: "MANTENIMIENTO"
    item:
      enabled: true
      slot: 3
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmFkYmE0MzY3MTM2YmFhYzFmNzY3Y2E3Y2IwZTU3N2UyYWUzYzFkYjQ5MWFjZThmNGRiM2Y4OTVjYzhkZDIifX19"
      name: "&b&lWRP Skyblock &7(Click)"

server-settings:
  update-interval-seconds: 10

scoreboard:
  enabled: true
  title: "&6&lWRP NETWORK"
  update-interval-seconds: 5
  lines:
    - "&7"
    - "&7Survival: %status_survival%"
    - "&7Skyblock: %status_skyblock%"
    - "&7"
    - "&7Jugadores: &f%players%/%max_players%"
    - "&1"
    - "&eplay.wrpnetwork.net"

messages:
  prefix: "&8[&6WRP&8]"
