name: SurvivalCorePlus
version: ${project.version}
main: net.wrpnetwork.survivalcore.SurvivalCore
api-version: '1.20'
authors: [Wyl, Ari]
description: Core de supervivencia, construcción y calidad de vida.
website: https://wrpnetwork.net
softdepend: [PlaceholderAPI]
commands:
  survivalcore:
    description: Comando principal de SurvivalCore+
    aliases: [sc]
  spawn:
    description: Teletransportarse al spawn
  tpa:
    description: Solicitar teletransporte a un jugador
  tpaccept:
    description: Aceptar solicitud de teletransporte
  tpdeny:
    description: Denegar solicitud de teletransporte
  back:
    description: Volver a la ubicación anterior o de muerte
  sethome:
    description: Establecer un hogar
  home:
    description: Ir a un hogar
  homes:
    description: Listar hogares
  delhome:
    description: Eliminar un hogar
  fly:
    description: Alternar modo vuelo
  repair:
    description: Reparar el objeto en mano
  buildmode:
    description: Alternar modo construcción
  tumba:
    description: Información sobre tu tumba
  money:
    description: Ver tu saldo
    aliases: [balance, bal]
  shop:
    description: Abrir la tienda
  eco:
    description: Administrar economía
  spawnnpc:
    description: Spawnear un NPC de tienda
  clan:
    description: Comandos de clan
  msg:
    description: Enviar mensaje privado
    aliases: [m, tell, w]
  reply:
    description: Responder último mensaje
    aliases: [r]
  clanchat:
    description: Chat del clan
    aliases: [c]
  togglechat:
    description: Alternar chat global
  tienda:
    description: Abrir la tienda de venta
